name: GitHub Profile Summary Cards

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "profile-summary-card-output/**"
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Summary Cards
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THEME: tokyonight
        with:
          USERNAME: actionanand
          AUTO_PUSH: true
